spring:
  session:
    store-type: none
  datasource:
    username: root
    password: tq26556570
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jeesite?serverTimezone=UTC
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
    url: jdbc:mysql://localhost:3306/jeesite?serverTimezone=UTC
    user: root
    password: tq26556570
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  cache:
    #    缓存及会话共享 是否决定开启redis缓存
    cluster-mode: false
#    清理全部缓存按钮所清理的缓存列表
#    clearNames: sysCache,corpCache,userCache,cmsCache,msgPcPoolCache
