spring:
  datasource:
    username: root
    password: yangwulang
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
