spring:
  application:
    name: platform
  flyway:
    enabled: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    clean-disabled: true
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    # 不同环境使用目录区分，在application-{}.yml中重写
#    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  profiles:
    active: unit



server:
  port: 8080
  servlet:
    context-path: /platform


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.loader.Loader: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace