spring:
  session:
    store-type: redis
  datasource:
    username: root
    password: yangwulang
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jeesite?serverTimezone=UTC
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
    url: jdbc:mysql://localhost:3306/jeesite?serverTimezone=UTC
    user: root
    password: yangwulang
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: 127.0.0.1
    port: 6379
    ssl: false
    database: 0
    password: yangwulang
    timeout: 2000
    lettuce:
      pool:
        max-idle: 3
        max-active: 20
  cache:
#    缓存及会话共享 是否决定开启redis缓存
    cluster-mode: true
#    清理全部缓存按钮所清理的缓存列表
#    clearNames: sysCache,corpCache,userCache,cmsCache,msgPcPoolCache
